### ISSUE TITLE
Popup position is calculated incorrectly and component goes "behind" the vertical scrollbar

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1289]
## I'm submitting a...
* Bug report 

## Current behavior
When a Popup needs to be opened near the right-hand part of the screen and there is a vertical scrollbar present, the position of the Popup is not calculated correctly, and it goes partially "behind" the scrollbar. Furthermore horizontal scrolling becomes impossible.

## Expected behavior
The Popup position is calculated correctly.

## Minimal reproduction of the problem with instructions

The issue can be observed in the following image and plunker:

![image](https://user-images.githubusercontent.com/7533599/35739122-48a8e3be-0839-11e8-9334-2abdde6ee3ba.png)

[https://plnkr.co/edit/A3rE0s5RXr5xQb7mXQWR?p=preview](https://plnkr.co/edit/A3rE0s5RXr5xQb7mXQWR?p=preview)

Open the DatePicker's Calendar. Try to scroll horizontally.

**Comment by danielkaradachki** [comment]
Should be fixed in the latest dev version of the popup:
https://plnkr.co/edit/jMSngwkz16SScd7UIdvn?p=preview

**Comment by ipeshev** [comment]
On second demo it is ok, but still reproducible on the first ( dev version used )

**Comment by ggkrustev** [comment]
Yep, the first one uses the official popup release, which doesn't include the fix. This will be resolved once the Popup Dev package is released officially.

**Comment by danielkaradachki** [comment]
The popup has been released and this should now work correctly with the example with the datepicker.

**Comment by ipeshev** [comment]
This is fixed in latest popup version - v2.4.0
