### ISSUE TITLE
DropdownList loses its value when filtering

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1377]
When using a DropdownList with filter and we type in some text in the filter then blur without selecting an option, the DropdownList loses its value.

Check the following sample plunker demonstrating the issue:
[https://plnkr.co/edit/Etqfpp2KWaGQbQAwpx0w?p=preview](https://plnkr.co/edit/Etqfpp2KWaGQbQAwpx0w?p=preview)
Steps to reproduce:
1. Click the DropdownList
2. Type in some text in the filter
3. Blur the DropdownList

**Comment by shulamitmisa** [comment]
Is there an estimate for when this is going to be fixed? I want to know how to handle our task internally (in our project).

**Comment by valchev** [comment]
@shulamitmisa the issue is fixed and the fix is available in dev version of the package.
Please install the latest dev version and give it a try.

**Comment by tsvetomir** [comment]
Fix released in v3.0.2 of the `@progress/kendo-angular-dropdowns`

**Comment by svetq** [comment]
The issue persists if a defaultItem is used:

[https://plnkr.co/edit/Etqfpp2KWaGQbQAwpx0w?p=preview](https://plnkr.co/edit/Etqfpp2KWaGQbQAwpx0w?p=preview)

1. Click the DropdownList
2. Type in some text in the filter
3. Blur the DropdownList
4. The DropDownList loses its "Small" value

**Comment by valchev** [comment]
Fix available in latest dev version.

@ipeshev the Needs-QA label is relevant for [this example](https://plnkr.co/edit/Etqfpp2KWaGQbQAwpx0w?p=preview)

**Comment by ipeshev** [comment]
Fixed in v3.0.3-dev.201806141007

**Comment by tsvetomir** [comment]
Shipped in v3.0.3
