### ISSUE TITLE
DropDowns reset() method does not clear the text from the component

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1780]
After an upgrade of the DropdownListModule from 2.x to the latest stable version the **reset()** method only resets the value field and not the text field:

Example: [https://stackblitz.com/edit/angular-f7dpzf-wzj24n](https://stackblitz.com/edit/angular-f7dpzf-wzj24n)

Same undesired behavior can be observed when the data items are objects with and without **valuePrimitive** set.

Note: reported in a support thread - Ticket ID: 1341261

**Comment by ipeshev** [comment]
The fix is available in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package v3.2.1-dev.201810300907.

**Comment by dimitar-pechev** [comment]
Shipped in `@progress/kendo-angular-dropdowns` v3.3.0.

**Comment by GenaANTG** [comment]
Problem is still alive. After calling reset, item selection stayed at the same place.
![screenshot from 2018-11-08 20-51-21](https://user-images.githubusercontent.com/12715550/48217630-f6cd8b80-e398-11e8-9bf6-fff690dc2661.png)

**Comment by dimitar-pechev** [comment]
@GenaANTG Thanks for your input!

I tried it out with both primitive and complex data, with and without a default item and I couldn't reproduce the issue. See [this example ](https://stackblitz.com/edit/angular-vfbcru)for reference.

The unwanted behavior at your end could be caused by the `package-lock.json` file which could hold a reference to the old dropdowns package. Try **deleting** it and running the following afterwards: 

```
npm install --save @progress/kendo-angular-dropdowns@latest
```

If I am missing something and the proposed solution doesn't solve the issue, please either provide more details on how to reproduce it. A runnable StackBlitz example would be best.

**Comment by GenaANTG** [comment]
@dimitar-pechev Thanks! Okay, i'll tried to delete package-lock.json and cache clean.

**Comment by GenaANTG** [comment]
@dimitar-pechev looks like problem still alive, Dimitar, i found few bugs with combobox. In short time i'll made report and reproduction.
