### ISSUE TITLE
TimePicker has performance issues in IE and Edge

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1836]
## I'm submitting a...
* Bug report 

## Current behavior
Whenever we use the TimePicker with other HTML elements or components on a single page, its performance is not as expected in IE and Edge.

## Minimal reproduction of the problem with instructions
Check the following example demonstrating this issue:
[https://stackblitz.com/edit/angular-65hvyd?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-65hvyd?file=src%2Fapp%2Fapp.component.ts)

and here is a video demonstrating the undesired behavior:
[https://www.screencast.com/t/gsFy0E1nw9v](https://www.screencast.com/t/gsFy0E1nw9v)

**Comment by l3ullet16** [comment]
Hello, I'm one of the developers who observed the bug. Can we ask for the status of this issue? Is it already being worked on your next release? Can we have an expectation on when to expect it? Any investigation results on what's exactly causing it between the two controls can also help so we can find a workaround ourselves.

Thanks,

Bullet

**Comment by l3ullet16** [comment]
@tsvetomir Hello, good day! I noticed you assigned this to yourself today. If you have any findings regarding what might be causing it, even if the fix is not there yet, please do care to share the cause as well if you have any suggested workarounds. Thank you very much!

**Comment by tsvetomir** [comment]
@l3ullet16 The cause is, without any doubt, the excessive number of change detection cycles triggered when interacting with the component. These slow down the entire application, not just the component.

We're on it and will publish an update in the dev channel in a few days.

**Comment by l3ullet16** [comment]
@tsvetomir Hi Tsvetomir, can you share where this Dev channel is so I can track any updates or will this thread be updated when a fix or a version of the control is released that has the fix? I just want to make sure I'm updated as soon as possible a fix is released. 

By the way, just a quick thought, is there any way that we can disable the some change detection atleast for IE as a workaround? Or some key features of the component will be deprecated thus not advisable as a workaround?

**Comment by tsvetomir** [comment]
I was referring to [Development Builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), sorry.

We have released the first batch of fixes in the latest development build, but the problem is challenging and we'll need more time to deal with it. It is not possible to influence this behavior from outside as the implementation of the component relies on these CD ticks to work.

This is [a snippet](https://stackblitz.com/edit/angular-esssng?file=src/app/app.component.ts) updated to that version. It's an improvement, but still quite unusable.

**Comment by l3ullet16** [comment]
@tsvetomir Thanks we did notice a bit of an improvement. But the trouble still persists most notably when there is a switch from AM to PM and vice versa; the hour ticker dial gets stuck moving up and down. Probably due to queued up events on the change detection being laggy or inconsistent in IE as you've earlier mentioned. Thank you for keeping us updated, Hopefully you find a permanent fix soon.

**Comment by l3ullet16** [comment]
@tsvetomir @svetq Hello everyone, just wanted to check with your Telerik if you can provide a target date for the fix for this bug? Our client is already highlighting the issue since we are nearing our project's end and this one is already a long standing bug. So atleast we can share this information to them and ease their waiting on the subject.

**Comment by danielkaradachki** [comment]
We are working on the issue but at this point we cannot commit to an exact time-frame.

**Comment by l3ullet16** [comment]
Hello, just wanted to follow up on this one. I would also like to reiterate as we have originally written on the ticket we logged before, that the issue only persists when we load the Kendo Timepicker and Kendo Datepicker TOGETHER on the same page in IE 11. Had to mention since it doesn't seem to be mentioned anywhere here. Both controls should be properly integrated with each other but there seems to be performance issues when both controls are being loaded in a IE 11 page.

With the information above mentioned, We really need a solution even for a temporary one, if you can already identify which parts of the two controls are problematic with each other, can you suggest if there's a version of both controls you could advise for us to use where the issue might be minimal or less?

**Comment by l3ullet16** [comment]
@danielkaradachki @tsvetomir Hello, haven't received any updates for almost two weeks. May we know the current status of the fix effort?

**Comment by danielkaradachki** [comment]
We will update the issue once there is a version with a fix. The problem is as mentioned by @tsvetomir, the amount of change detections triggered by the component. A possible way to mitigate the problem for the moment is to wrap components that take more time for change detection like the grid in an OnPush component so  that they are not checked:

https://stackblitz.com/edit/angular-zazhph?file=src%2Fapp%2Fapp.component.ts

**Comment by danielkaradachki** [comment]
The latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version should reduce the number of change detections triggered by the timepicker and the other components. Please give it a try and let me know how it goes.

**Comment by danielkaradachki** [comment]
The changes are released in 3.5.2

**Comment by tsvetomir** [comment]
All pending fixes are shipped in v3.5.2 of `@progress/kendo-angular-dateinputs`
