### ISSUE TITLE
Auto complete and multi select do not work in IE11

### ISSUE THREAD

**Issue by brazillt123** [telerik/kendo-angular#191]
Works in Chrome, but not IE11:
From your demo page:
http://www.telerik.com/kendo-angular-ui/components/dropdowns/

When you type in the input the text is not visible in IE11.

**Comment by KirilNN** [comment]
The problem comes form the flexbox use on `inputs` in IE11. Assigning to @joneff

**Comment by inikolova** [comment]
Autocomplete issue fixed with this commit -> https://github.com/telerik/kendo-angular-dropdowns/commit/410189b857b8847b8ca0baa6be52befcd670a523

**Comment by ngreniermajor** [comment]
It seems like this issue came back, at least with the multiselect component.  
See demo page: http://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/
