### ISSUE TITLE
When lock is used, some times the table is truncated

### ISSUE THREAD

**Issue by jiangen1016** [telerik/kendo-angular#2177]
When used lock to fixed table, if data is so many, table can do scroll. the  last tr for lock will be truncated. This cannot be displayed. 
<img width="1216" alt="table" src="https://user-images.githubusercontent.com/22633149/55536179-ad852c00-56eb-11e9-825c-cf3d66bf8220.png">
Angular version is 6.1.10 and @progress/kendo-angular-grid is 3.13.1

**Comment by jiangen1016** [comment]
I solved the problem, please close this, thanks.

**Comment by jiangen1016** [comment]
@tsvetomir Oh, the problem still exists, it appeared in other table when used lock

**Comment by tsvetomir** [comment]
@jiangen1016 Can you please share a runnable example to help us reproduce the issue?

**Comment by jiangen1016** [comment]
> @jiangen1016 Can you please share a runnable example to help us reproduce the issue?

only runnable, or need code ?

**Comment by jiangen1016** [comment]
@tsvetomir  When I used locked property for for two kendo-grid-column  at the same time. They will be happen

**Comment by tsvetomir** [comment]
The demo for [Locked Columns](https://www.telerik.com/kendo-angular-ui/components/grid/columns/locked/) applies `locked` to two columns. I don't see the issue there.

Can you for the demo on StackBlitz and modify it to match your scenario more closely?

**Comment by jiangen1016** [comment]
Hi, @tsvetomir. Thank you for you remind me. I reappear this issue on stackblitz. And you can see [https://angular-d5cemc-nydahy.stackblitz.io](url) If grid data is remote, (I used setTimeout to simulate this), and kendo-grid not to set height. there will be truncated. In my project has many table used lock and data is remote.

**Comment by jiangen1016** [comment]
Do not just two for lock, just one, they will be truncated also.

**Comment by ipeshev** [comment]
Fixed in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by jiangen1016** [comment]
Yes, that is working. Thanks

**Comment by kdubious** [comment]
Still an issues under these conditions:
1. No Height set on grid, always has an issue
2. Using `[kendoDataBinding]` and `pageable='true'` adds to the issue
Here's a demo: [https://stackblitz.com/edit/angular-trywwh](url)

**Comment by kdubious** [comment]
@ipeshev & @tsvetomir, definitely an issue related to no defined height on the grid. Do you have a demo / better method of dynamic grid height?

**Comment by ipeshev** [comment]
@kdubious  https://www.telerik.com/kendo-angular-ui/components/grid/advanced-features/responsive/#toc-height this is the only way by now, but there is catch with setting height this way that comes from CSS itself.

**Comment by tsvetomir** [comment]
Fixed in v3.14.2

**Comment by tsvetomir** [comment]
Still broken in the case described by @kdubious - sorry!

**Comment by danielkaradachki** [comment]
@kdubious 

The problem should be fixed in the latest dev version:
https://stackblitz.com/edit/angular-a3taqs?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Fixed in 4.0.0

https://stackblitz.com/edit/angular-eun6x4?file=app/app.component.ts
