### ISSUE TITLE
[Scheduler] Recurrence editor "After ... occurrences" input is disabled when value is deleted

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2290]
The NumericTextBox used for editing the number of occurrences after which an event should be finished becomes disabled once the value is removed, and the user cannot focus it again to choose a value:

[https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/editing-directives/#toc-setup](https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/editing-directives/#toc-setup)

![image](https://user-images.githubusercontent.com/7533599/58541585-8129ef80-8204-11e9-9421-2fe1fd2c264c.png)

**Comment by Raisolution** [comment]
Fix is available in `v0.13.1-dev.201905310724`

**Comment by Seshuggina** [comment]
Issue still exists, Recurrence end inputs fields disabled.

![image](https://user-images.githubusercontent.com/1551596/60883421-ce6b9900-a267-11e9-8cd0-4adc9f79d433.png)

**Comment by Raisolution** [comment]
Hi @Seshuggina 

Is this a screenshot from the Angular or the jQuery version of the Scheduler?

**Comment by Seshuggina** [comment]
Angular (2 & above).  Changed the styles of radio and checkboxes

**Comment by Raisolution** [comment]
We are unable to reproduce the issue on our end. Is it possible to provide a Stackblitz example of the same?

**Comment by Seshuggina** [comment]
Iusse is happening due click (actually [outside Click directive](https://christianliebel.com/2016/05/angular-2-a-simple-click-outside-directive/)) event in the navigation menu. If I remove it, edit scheduler is working fine.

**Comment by Jesse-imuzo** [comment]
@Seshuggina I'm having the same issue. How did you fix this?

**Comment by Seshuggina** [comment]
It might happen if your project angular version is not same as Kendo Angular Version.
