### ISSUE TITLE
[Sortable] addDataItem with index 0 when there is a single item adds to the wrong index

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#2295]
**Describe the bug**
When you have a single item in the sortable and call `addDataItem(..., 0)` the data item is added to the end instead of adding to start. 

**To Reproduce**
https://stackblitz.com/edit/angular-cwrcq9-qxw3j2?file=app/app.component.ts
Press "Add New Item" - "Item 2" will be added after the existing "Item 1" although `addDataItem` is called with `index = 0`. If you press the button one more time you will see that "Item 3" will be added correctly at the start. 

**Expected behavior**
Adding with index 0 should always add to the start.

**Comment by siyka-marinova** [comment]
Fixed in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-sortable`

**Comment by PeterStaev** [comment]
@siyka-marinova this still doesn't work fully correctly. For example if you have 2 items and you use `addDataItem("test", 1) it adds it to the end, when it should be added to the mid:
https://stackblitz.com/edit/angular-cwrcq9-qxw3j2?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-sortable v3.0.4`
