### ISSUE TITLE
Dropdowns grouping issue

### ISSUE THREAD

**Issue by baltyan** [telerik/kendo-angular#2520]
![kendo_issue (1)](https://user-images.githubusercontent.com/9678938/66433074-8e67ae00-ea30-11e9-8e13-62bb7d6f7765.gif)

The grouping first value is not shown or shows wrong value depending on position of dropdown in the page.

https://stackblitz.com/edit/angular-5ej18g?file=app/app.component.ts

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version 77.0.3865.90

**Comment by vaheprog** [comment]
We have same problem. 
Do you have any update? Because of this we can't go PROD.
Can you do hotfix or give us some workaround for this issue?

Thx

**Comment by Janjuks** [comment]
Workaround that worked for me was to always put some dummy group at the front of your group data and hide it with css.
https://stackblitz.com/edit/angular-5ej18g-imeyvi

**Comment by vaheprog** [comment]
Janjuks - that works but it doesn't fix the group at the top.

**Comment by mbechev** [comment]
Also, the issue is reproduced when popupSettings option **appendTo** property is set to '_component_'. The group header is not changed when scrolling the MutliSelect items.

Here is an example:
https://stackblitz.com/edit/angular-heyuhc?file=app/app.component.ts

**Comment by svetq** [comment]
A similar undesired behavior is observed only in IE 11 when running the example from the following article:

https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/grouping/

**Comment by tapopov** [comment]
Fix is available in the [latest dev release](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) (v4.2.8-dev.202005280652).

**Comment by gkarapeev** [comment]
Fixed in version v4.3.0

**Comment by chetanmore0510** [comment]
This is still not working on the version "@progress/kendo-angular-dropdowns": "^5.4.0"

**Comment by gmadhusudan345** [comment]
I tried to use CSS border radius 6px and below to kendo grouping dropdown list item and the grouping first value(grouping title) is visible perfectly.
`.k-list .k-list-item {
    border-radius: 6px;
}`

Please check below recorded video and screenshot:
[dropdown group issue.webm](https://user-images.githubusercontent.com/40488115/195319618-37d509a3-7616-4dec-b6be-2bc0d25bd431.webm)


![dropdown-grouping](https://user-images.githubusercontent.com/40488115/195319983-3cd77a61-466c-4951-a688-06b0cd129964.png)
