### ISSUE TITLE
[Chart] Donut chart with "autoFit" throws an error with multiple series and no data

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2643]
When there are multiple series items, and **autoFit** is set to **_true_**,  the Chart throws a JavaScript error in the console if data is retrieved asynchronously and is not initially available:

https://stackblitz.com/edit/angular-7cfzjc-w8byyb?file=app/app.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by eghelbe** [comment]
downloaded the latest dev version ("@progress/kendo-angular-charts": "^4.1.3-dev.201912181239")
issue still persist :(

**Comment by siyka-marinova** [comment]
Fix for this issue is now also available in `kendo-angular-charts v4.1.3`
