### ISSUE TITLE
Tooltip sometimes overridden by browser default tooltip

### ISSUE THREAD

**Issue by tipag** [telerik/kendo-angular#2708]
## I'm submitting a...
* Bug report

## Current behavior
If a tooltip is open and an underlying element is hovered above, the underlying element's tooltip is sometimes shown as the browser's default tooltip.

![tooltipkendo](https://user-images.githubusercontent.com/22882432/73050921-a9481c00-3e81-11ea-8b3d-bf4dc8b1ef60.PNG)

## Expected behavior
Kendo tooltip should always override browser default tooltip.

## Minimal reproduction of the problem with instructions
Here is a sample where the problem can be reproduced:
https://stackblitz.com/edit/angular-ejbb9x

hover over the button on the bottom, make sure tooltip is shown, then move the mouse over the tooltip to the button on the top. No tooltip is shown. Move the mouse (make sure not to leave the button) to show tooltip. Sometimes the default browser tooltip is shown instead of the kendo tooltip.
Repeat this action multiple times if it does not happen on the first try.

## Environment
I only added a line break in the standard tooltip sample from the current kendo angular tooltip sample. (https://www.telerik.com/kendo-angular-ui/components/tooltip/default-conf/) So it happens in the current version.

Browser:
- Chrome (desktop) version 79.0.3945.117
- Firefox version 68.4.1esr

I only managed to achieve this behaviour if a tooltip is already open and I move the mouse over this tooltip to an underlying element which also has a title set. So I could imagine something like the first tooltip somehow closing the second as well, or the first open tooltip preventing the second to trigger at all.

**Comment by svetq** [comment]
also requested in private support thread 1451983

**Comment by yanmariomenev** [comment]
Wanted to add a quick video demonstrating the undesired behavior:
http://somup.com/criDiPYFlS
StackBlitz demo:
https://stackblitz.com/edit/angular-dhdagx?file=app%2Fapp.component.ts

**Comment by JonathanGagaga** [comment]
Meet similar problem, but the difference is that in my case the tooltip is displaying the chrome default style all the time. I tried several methods of changing css styles of the tool tip, none of them would work.

https://www.telerik.com/forums/tooltipclass-not-working
https://www.telerik.com/kendo-angular-ui/components/tooltips/get-started/#toc-using-the-components
https://www.telerik.com/forums/how-can-i-change-to-look-of-tooltips-
https://stackoverflow.com/questions/34656674/kendo-ui-change-tooltip-color

**Comment by Raisolution** [comment]
@JonathanGagaga the described problem does not seem related to the initial one in this issue. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for further assistance with the specific scenario.

**Comment by Raisolution** [comment]
Fix is available in `v4.0.1` of the Tooltips package.

**Comment by khitrukhina** [comment]
This is issue wasn't fixed and still present in 11.2.0. With showOn option set to hover it shows the title, without this options it shows nothing )
![image](https://github.com/telerik/kendo-angular/assets/79148060/21a9fec7-794d-4efc-a931-9901370ebe5a)
