### ISSUE TITLE
[TreeView] inconsistent behavior

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2738]
**Describe the bug**
When checking a parent item and then expanding its child nodes, the child nodes get checked as well. After expanding all levels and then collapsing the root element the child elements are no longer checked on expanding.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-cnzlah-owhnnb?file=app/app.component.ts

 1. Check "user 1",
 2. Еxpand the "User 1" node,
 3. Еxpand the "User 2" node.
 4. Uncheck user 1",
 5. Collapse the "User 1" node,
 6. Check user 1",
 7. Еxpand the "User 1" node, 
    *** now the child nodes are not being checked

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-treeview`

**Comment by ravirasadiya** [comment]
It is still nor resolved in latest dev build

**Comment by dimitar-pechev** [comment]
The fix is already released in **v4.1.3** of the **TreeView** package. [Here's a working example](https://stackblitz.com/edit/angular-cnzlah-jzdyb8).

Closing the issue, as I believe it is resolved. @ravirasadiya, feel welcome to comment if I'm missing something. We'll reopen the thread if that's the case.

**Comment by ravirasadiya** [comment]
Hi, I have checked that link which you have shared for the fix but as I am seeing it is not resolved yet.let me give you scenario
1) checked user 1
2) expand user 1 node
3 ) collapsed user 1 node
4) now uncheck node 1

Now you will see that it is in intermediate state rather than uncheck and all the child node are also selected yet

Thanks

**Comment by dimitar-pechev** [comment]
This behavior is unrelated. The issue is tracked here https://github.com/telerik/kendo-angular/issues/2387. We don't have a fix for it as of yet. For the moment a custom check.directive implementation is the straight-forward solution for this. If we cannot find a good way to fix the problem, we'll offer a how-to demo with a custom implementation that handles this scenario. 

If you need help with such an implementation, please open a support ticket.
