### ISSUE TITLE
[RangeSlider] Range slider ticks not working properly

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3262]
**Describe the bug**
Dragging the slider ticks fast can pass the other slider tick and bug out the UI. This behavior can be seen in the video provided below.

**To Reproduce**
Start sliding fast the first or second tick so they pass each other.
Short video recording of the bug : https://screenrec.com/share/ne5Kt4G1lu
Work on any demo of the RangeSlider component : https://www.telerik.com/kendo-angular-ui/components/inputs/rangeslider/

**Workaround**
https://stackblitz.com/edit/rangeslider-tick-workaround?file=app/app.component.ts (doesn't work with the latest versions)

**Screenshots**
https://imgur.com/a/Aw0WSOU

**Browser**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [89...latest]

**Comment by michaelmarcuccio** [comment]
From what I can see, none of the links in this issue work. They all go to https://github.com/telerik/kendo-angular/issues/url

**Comment by yanmariomenev** [comment]
The issue seems to be present even if the user doesn't drag the tick fast.
Example - https://stackblitz.com/edit/angular-uvoafb-kfvewf?file=app%2Fapp.component.ts
Behavior - https://screencast-o-matic.com/watch/c3nXi9Vbc5Q
Example with smallStep and largeStep - https://stackblitz.com/edit/angular-27fdaa?file=app/app.component.ts
Behavior - https://screencast-o-matic.com/watch/c3nXiRVbc5Y

**Comment by Raisolution** [comment]
Fix available in `v8.0.9` of the Inputs package.

**Comment by PaskalevStoyan** [comment]
The reason this behaviour still persists in the RangeSlider drag handles is because, when an HTML element is wrapped in an iframe, its events don't propagate outside the iframe, resulting in the observed discrepancy between the drag handles.

The demos in the Kendo Angular documentation and the StackBlitz examples are wrapped in an iframe, thus the reason why it can be seen on both places.

This is browser specific behaviour observed only in Chrome - for more information - please see this issue in the [Chromium bug report website](https://bugs.chromium.org/p/chromium/issues/detail?id=522109).
