### ISSUE TITLE
[ToolBar] showText functionality not working properly with Ivy

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3631]
**Describe the bug**
When ToolBar [showText](https://www.telerik.com/kendo-angular-ui/components/toolbar/api/ToolBarButtonComponent/#toc-showtext) option is set to "overflow", the button text is still displayed while the button is in the toolbar .

**To Reproduce**
Run the following project:
[toolbar-issue.zip](https://github.com/telerik/kendo-angular/files/8339410/toolbar-issue.zip)
Correct behavior in Angular 9 - https://stackblitz.com/edit/angular-wsjdhb?file=app/app.component.ts

**Screenshots**
Issue:
![chrome_UwBitN5hGh](https://user-images.githubusercontent.com/49076727/159869650-d3aaf7d3-240c-436c-a9a3-3dc43e91b823.png)

Expected:
![chrome_DUbFif2WrA](https://user-images.githubusercontent.com/49076727/159869226-93fe499e-96a9-45f4-86bc-ef7464c538b3.png)

**Comment by Raisolution** [comment]
Fix available in `v6.0.2` of the Toolbar package.

**Comment by yanmariomenev** [comment]
I am reopening the issue as the fix works for the ToolBarButtonComponent. However, the issue remains with ToolBarDropDownButtonComponent and ToolBarSplitButtonComponent as demonstrated in the following example:

https://stackblitz.com/edit/angular-6tppsd?file=src%2Fapp%2Fapp.component.ts

**Comment by Raisolution** [comment]
Fix available in `v6.1.1` of the Toolbar package.
