### ISSUE TITLE
Locked column height is not updated when setting Grid data programmatically

### ISSUE THREAD

**Issue by ChrisProlls** [telerik/kendo-angular#570]
I just tested the grid with automatic binding (very clean solution) and fixed columns. It's seems that the locked columns don't follow the height of columns which are not locked. 
Plunker : http://plnkr.co/edit/p9YbkzpnMJhE3JCln7sw?p=preview.
The result is something like this :
![capture](https://cloud.githubusercontent.com/assets/1511666/26202940/8a348180-3bd9-11e7-82fb-442aeb89a09f.PNG)

**Comment by rkonstantinov** [comment]
Hey @ChrisProlls ,

The behavior in question is due to the fact that when setting the data programmatically via the Grid component data field, the change detection for the Grid Component will not be triggered. And the component will not be notified in order to run the routine for syncing the rows height. To overcome this Grid's `onDataChange` method should be called (it is called automatically by the `DataBindingDirective`'s `rebind` method, however with the custom directive in question it is overridden):

```typescript
     public ngOnInit(): void {
        this.serviceSubscription = this.products.subscribe((result) => {
            this.grid.data = result;
            this.grid.onDataChange();//<<<<<<<
        });

        super.ngOnInit();

        this.rebind(); 
    }
```

**Comment by ChrisProlls** [comment]
It's works, thanks !

**Comment by tsvetomir** [comment]
This should be fixed now, [see plunkr](http://plnkr.co/edit/MbzsV2fHQFJbCC4zKSdB?p=preview).

**Comment by siyka-marinova** [comment]
Reproducible with the above [plunker](http://plnkr.co/edit/MbzsV2fHQFJbCC4zKSdB?p=preview) and kendo-angular-grid v.1.2.3
https://www.screencast.com/t/SU4HdZq6

**Comment by tsvetomir** [comment]
Should be fixed in v1.2.4-dev.201707251109

**Comment by siyka-marinova** [comment]
Fix is available in the latest dev. version of `@progress/kendo-angular-grid`. To get this version, specify in package.json:
`"@progress/kendo-angular-grid": "dev"`

**Comment by tsvetomir** [comment]
Fix shipped in v1.3.1

**Comment by kdubious** [comment]
Seems to be broken again in    
`"@progress/kendo-angular-grid":` "^3.12.1",

**Comment by tsvetomir** [comment]
@kdubious can you give the [development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) a shot? We fixed something similar recently (https://github.com/telerik/kendo-angular/issues/2177).

**Comment by kdubious** [comment]
Same issue, commented over in #2177, pasted below

--
Still an issues under these conditions:
1. No Height set on grid, always has an issue
2. Using `[kendoDataBinding]` and `pageable='true'` adds to the issue
Here's a demo: [https://stackblitz.com/edit/angular-trywwh](url)

**Comment by gs-saagarwal** [comment]
> Hey @ChrisProlls ,
> 
> The behavior in question is due to the fact that when setting the data programmatically via the Grid component data field, the change detection for the Grid Component will not be triggered. And the component will not be notified in order to run the routine for syncing the rows height. To overcome this Grid's `onDataChange` method should be called (it is called automatically by the `DataBindingDirective`'s `rebind` method, however with the custom directive in question it is overridden):
> 
> ```ts
>      public ngOnInit(): void {
>         this.serviceSubscription = this.products.subscribe((result) => {
>             this.grid.data = result;
>             this.grid.onDataChange();//<<<<<<<
>         });
> 
>         super.ngOnInit();
> 
>         this.rebind(); 
>     }
> ```

This works from 2nd time but the Issue persists on loading the page initially. Can you please provide a solution for this?

**Comment by tsvetomir** [comment]
Seems to be working with the latest version, see [updated demo](https://stackblitz.com/edit/angular-trywwh-fdae3m?file=app/app.component.ts).
