### ISSUE TITLE
NumericTextBox dragging issue

### ISSUE THREAD

**Issue by jamesomac** [telerik/kendo-angular#892]
## I'm submitting a...
* Bug report

## Current behavior
In Google Chrome when two numerictextboxes are side by side, clicking and dragging (in one motion) the left textbox to the right causes the text to be dragged to the other box.

## Expected behavior
When clicking and dragging the left numerictextbox to the right, the text should be highlighted or not based on cursor location.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/d58qouWnlqvrsltnryL6

Using Google Chrome, click and drag the text from the left textbox to the right textbox.

## Environment

Browser:
- Chrome (desktop) version 60
- IE version 11

System:
- TypeScript version: 1.0.3.0
- Node version: 7.10.0
- Platform:  Windows

This problem only seems to occur in Google Chrome. It works as expected in Internet Explorer 11.

**Comment by jamesomac** [comment]
Hello,

It appears this incident has been closed, yet I am still having this problem on multiple machines. I have tested my example plunkr and the issue still exists.

Has this bug been fixed?

Are you not able to reproduce and require more information?

What can I do about this?

Regards,

**Comment by danielkaradachki** [comment]
Hi, 
An official version(1.3.1) with the fix was just published. Previously the fix was available only in the dev channel.

**Comment by jamesomac** [comment]
Hello,

Sorry to add to this topic so far after it being closed (I've been out of the loop), but I have been informed the issue still exists in the newer versions. I have tried updating to version 1.4.2 of the kendo inputs and the issue persists.

The issue can still be seen on [this page](https://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/formats/) of the kendo documentation and still only in Google Chrome.

Please advise.

**Comment by danielkaradachki** [comment]
Dragging seems to be correctly performed at least on my side in the demo. Perhaps I have misunderstood the issue. Is the problem with the drag position or that the text is being dragged at all? The second, depends on the browser behavior for input with selection:
http://plnkr.co/edit/ySfNPcSTzYHZmHlbpA3e?p=preview
