### ISSUE TITLE
Hours/minutes cannot be selected reliably in IE11 via mouse

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#981]
In IE 11, when trying to pick the hour/minutes in the drop down via mouse clicks, the clicked number sometimes does not get selected, but is only scrolled to instead.

The issue is observable in the online demos:

[https://www.telerik.com/kendo-angular-ui/components/dateinputs/timepicker/](https://www.telerik.com/kendo-angular-ui/components/dateinputs/timepicker/)

Reported by customer in TicketID: 1134050

**Comment by ggkrustev** [comment]
The issues is fixed in the latest @dev version of @progress/kendo-angular-dateinputs. Just install the @progress/kendo-angular-dateinputs@v1.4.0-dev.201710310730 and give it a spin.

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.4.0` is out. It includes the fix. Will close the issue as fixed.
Please feel free to comment if something is not correct.

**Comment by ToxicToast** [comment]
Sorry for reopening this - but it looks like that the "bug" isnt fixed yet.
The Timepicker closes instantly after selecting it on IE

I should mention that the Picker gets opened inside a Dialog

@angular/core: 5.2.9
@progress/kendo-angular-dateinputs: ^3.4.4,
@progress/kendo-angular-dialog: ^3.7.0
